### ISSUE TITLE
Missing vendor.css on grunt build

### ISSUE THREAD

**Issue by eversoclever** [robinpokorny/generator-lessapp#11] opened 2014-09-03 03:47 UTC
![screen shot 2014-09-02 at 10 46 27 pm](https://cloud.githubusercontent.com/assets/6600820/4129299/0f5d64c6-331d-11e4-8c36-dbe590c92846.png)

**Comment by robinpokorny** [comment] 2015-04-03 08:47
Grunt only handles main.less, if you want other files to be processed you need to manually configure it in Gruntfile.

I will close this issue as it seems to me that it is not a bug. If you have follow-up questions please continue in this thread for future reference.

**Closed by robinpokorny** 2015-04-03 08:47 UTC
